### ISSUE TITLE
package built for arch all error

### ISSUE THREAD

**Issue by erdoukki** [erdoukki/fail2ban_openwrt#7]
```
root@NSA310S:~# opkg install *.ipk --force-checksum
Unknown package 'fail2ban'.
Unknown package 'fail2ban'.
Unknown package 'python3-pyinotify'.
Collected errors:
 * pkg_hash_fetch_best_installation_candidate: Packages for fail2ban found, but incompatible with the architectures configured
 * opkg_install_cmd: Cannot install package fail2ban.
 * pkg_hash_fetch_best_installation_candidate: Packages for fail2ban found, but incompatible with the architectures configured
 * opkg_install_cmd: Cannot install package fail2ban.
 * pkg_hash_fetch_best_installation_candidate: Packages for python3-pyinotify found, but incompatible with the architectures configured
 * opkg_install_cmd: Cannot install package python3-pyinotify.

```
In Makefiles ; 
`PKGARCH:=ALL`

but packages look not to being arch all !?

**Comment by peci1** [comment]
Yeah, it doesn't install on my Turris Omnia: Linux turris 4.14.222 #0 SMP Wed Mar 3 11:38:36 2021 armv7l GNU/Linux

I can test further packages if you want.

**Comment by peci1** [comment]
I tried binaries from https://github.com/erdoukki/fail2ban_openwrt/tree/master/binary/master .

**Comment by erdoukki** [comment]
Yes, normal, as said the build is not multiarch.
You may need to build the package.

**Comment by erdoukki** [comment]
> 
> `PKGARCH:=ALL`
> 
> 
> but packages look not to being arch all !?

To fix we can try with ;

`PKGARCH:=all`

**Comment by erdoukki** [comment]
actually fail2an is mainline in master and also 21.02
